spring:
  config:
    import:
    - optional:configserver:http://localhost:9005

  profiles:
    active:
    - product-service
  
    
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"