server:
  port: 8001
  compression:
    enabled: true
    min-response-size: 4096
    mime-types:
    - application/json
            
logging:
  level:
    org:
     hibernate:
       type: TRACE
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:3000/emp_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
